# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
future: 			 false
markdown: 			 redcarpet
#relative_permalinks: true

# Setup
title:               Türkiyede Elektrik Üretimi
tagline:             '1970-2013 Yılları Arası'
description:         'Türkiyede 1970 ile 2013 yılları arasında üretilen elektrik enerjisinin dağılımı '
url:                 
baseurl:             '/enerji-2016'
paginate:            5

# About/contact
author:
  name:              'Takım elemanları'
  url:               
  email:             

# Custom vars
version:             1.0.0
encoding: UTF-8